CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name TEXT NOT NULL,
    username TEXT NOT NULL UNIQUE,
    email_address TEXT NOT NULL,
    password TEXT NOT NULL,
    date_created TIMESTAMP NOT NULL DEFAULT now()
);

INSERT INTO users (full_name, email_address, username, password)
VALUES
    ('Jacob Mead', 'thisemailaddress@yahoo.com', 'jacobmead', '$2a$12$SYOCbT5wm9WTFDSQhhLG5e9czskJ5M4SlcVSss1/jKRJZheMYPNc6'),
    ('James Gatluak', 'jgatluak@gmail.com', 'jgatluak', '$2a$12$0YVinq2AAem46yQ9VenxEeBnobnPtlNL4J2nFzw4DNlvn3DbwITHe'),
    ('John Malual', 'malualj@hotmail.com', 'johnnym',  '$2a$12$GDVDiFUwyjcP5vOXXZkgxuuHB/8mG3slUVSpKdwxUARn0rixkPvK6'),
    ('Chol Deng', 'chol@deng.com', 'choldeng', '$2a$12$ETDFrc04wGyj3xw4BR9R4eUo86wMzX.Ub2zNyxBPHQRZUmJBdgF8i'),
    ('Demo Account', 'demo_account@email.com', 'demo', '$2a$12$FBRiDsWdr3xFcSksdFLCw.M2qDwEnkBc9Y59Uz3ft/FF3F0edrtY.')
;
