CREATE TABLE expense (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    expense DECIMAL(10, 2) NOT NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    description TEXT,
    date_created TIMESTAMP NOT NULL DEFAULT now()
);

INSERT INTO expense (expense, user_id, description)
VALUES
    (2.95, 1, 'coffee'),(14, 1, 'tea'),(1.99, 1, 'groceries'),(12.99, 1, 'video games'),(5.99, 1, 'milk'),(100, 1, 'movie tickets'),(20.99, 1, 'dog food'),
    (2.95, 2, 'coffee'),(14, 2, 'tea'),(1.99, 2, 'groceries'),(12.99, 2, 'video games'),(5.99, 2, 'milk'),(100, 2, 'movie tickets'),(20.99, 2, 'dog food'),(2.95, 3, 'coffee'),(14, 3, 'tea'),(1.99, 3, 'groceries'),(12.99, 3, 'video games'),(5.99, 3, 'milk'),(100, 3, 'movie tickets'),(20.99, 3, 'dog food'),(2.95, 4, 'coffee'),(14, 4, 'tea'),(1.99, 4, 'groceries'),(12.99, 4, 'video games'),(5.99, 4, 'milk'),(100, 4, 'movie tickets'),(20.99, 4, 'dog food'),(2.95, 5, 'coffee'),(14, 5, 'tea'),(1.99, 5, 'groceries'),(12.99, 5, 'video games'),(5.99, 5, 'milk'),(100, 5, 'movie tickets'),(20.99, 5, 'dog food')
;
